### ISSUE TITLE
Header cuts off body

### ISSUE THREAD

**Issue by darkpixel** [rossp/django-helpdesk#286]
We have several deployments of django-helpdesk for clients that need a basic ticket system.  Most of them have custom graphical tweaks, so I thought the 'header cuts off body' issue was something I did.

After a recent setup that had no customization, I noticed it was still cutting off the body.  See the following two screenshots taken using Chrome under Linux Mint 17.1 and Windows.  Firefox under Linux and Windows as well as IE under Windows appear to render it correctly.  Just not Chrome.

![cutoff1](https://cloud.githubusercontent.com/assets/158380/5622363/448db3e4-94f7-11e4-96e4-fda34420b86f.png)
![cutoff2](https://cloud.githubusercontent.com/assets/158380/5622364/449123d0-94f7-11e4-9d87-1590a309b48f.png)

**Comment by rossp** [comment]
Interesting. I'm unable to reproduce locally and the demo site (https://django-helpdesk-demo.herokuapp.com) doesn't overlap like this when I'm using both IE and Chrome (on Windows). I don't have a Linux or Mac desktop available to test with unfortunately. 

Are you able to tell why this is happening? Is it a particular class or style definition causing it? 

![django-helpdesk demo screenshot](https://cloud.githubusercontent.com/assets/91261/5640841/4c786628-9680-11e4-89e3-da0d8cd3c717.png)
![django-helpdesk demo screenshot 2](https://cloud.githubusercontent.com/assets/91261/5640842/4c7aabcc-9680-11e4-9642-51c3d0cd0a85.png)

**Comment by darkpixel** [comment]
Hmm....tried it with my chrome extensions disabled, same issue.  Tried it on a new Linux Mint box, same issue.  The particular install I'm testing against was created by:
```
mkvirtualenv helpdesk
pip install django-helpdesk
django-admin createsite helpdesksite
```

Tweaked the settings.py and urls.py to include the necessary references.

*wonders if it's an out-of-date package*?  Maybe I should pip install directly from the repo.

Give me a few hours to get un-buried and I'll give it a shot.

**Comment by rossp** [comment]
Hi, I've just re-tested in a fresh virtualenv using both the PyPi package (0.1.14) and the latest from GitHub. Neither show this issue when tested on Chrome 39.0.2171.95 m, IE 11.0.9600.17498, or Firefox 34.0.5 (All on Windows 8.1) 

Is there perhaps something proxying / overwriting the bootstrap.min.css file? It's being loaded from a CDN, perhaps something is interfering with that?

**Comment by darkpixel** [comment]
I'll have to do more digging on my end.  It's obviously something with a few of my deployments.

**Comment by rossp** [comment]
I've just done a fresh install on a different server (even though the server appears to be configured exactly the same way) and I'm seeing this header issue, too. I'm seeing 404 errors with the way it's trying to load helpdesk-extend.css, which means we're probably missing a few items. Static files appear to be updated properly, however the URLs to staticfiles in `templates/base.html` are wrong.

**Comment by rossp** [comment]
Confirmed this is due to `django.core.context_processors.request` not being in the default `TEMPLATE_CONTEXT_PROCESSORS` and this isn't documented as a requirement for django-helpdesk. Rather than getting users to modify their settings, I have an easy confirmed fix; in `templates/base.html` add to the very top:

`{% load static from staticfiles %}`

Then, for each call to `{{ STATIC_URL }}` replace with eg `{% static "helpdesk/helpdesk-extend.css" %}`. 

I'm not able to do a git commit or pull request right now but will get to it in next 48 hrs.

**Comment by reduxionist** [comment]
I too encountered this issue and the given fix worked as promised. I am submitting a PR for this change, which also applies it to templates/public_base.html as it is needed there as well.
