### ISSUE TITLE
Two or more email addresses!

### ISSUE THREAD

**Issue by xlamys** [rossp/django-helpdesk#288]
Hi!
I have a question.
If I have some emails on the which sent tickets.
There are difficulties with the addition?

**Comment by rossp** [comment]
I don't quite understand your question, sorry. can you please clarify?

**Comment by jitbit** [comment]
I believe TS means two or more emails assigned to a user-account.

**Comment by rossp** [comment]
That can't be done because we use the standard Django `User` model.

Given the requester hasn't clarified anything in a year, I'm closing this. Happy for it to be re-opened when more info is available.
