### ISSUE TITLE
Django 1.6 installation - emailtemplate initial fixtures

### ISSUE THREAD

**Issue by flinz** [rossp/django-helpdesk#294]
The commit https://github.com/rossp/django-helpdesk/commit/b53d3ad9bc4b6561542dffd1bdf16e2a3cd59308 renamed the ```fixtures/initial_data.json``` to ```fixtures/emailtemplate.json```. However, on Django 1.6 this causes no loading of the initial emailtemplates, which in turn makes sending emails impossible.

I propose to either
- change the name back to ```initial_data.json``` and correct documents linking to this name (tests and django migrations)
- create a south data migration that takes care of importing this.
- mention in the documentation one would have to run ```./manage.py loaddata emailtemplate.json``` post migration manually

**Comment by rossp** [comment]
Renaming back to `initial_data.json` is dangerous in 1.6 as [it'll be re-loaded every time migrations run](https://docs.djangoproject.com/en/1.7/howto/initial-data/#automatically-loading-initial-data-fixtures) - so any template edits will be lost. 

I prefer the 3rd option - a documentation update - as it'll work in both <=1.6 and 1.7+ - and e-mail templates are probably something the installing user should be able to control.
