### ISSUE TITLE
Django 1.6: User.post_save usersettings creation fails.

### ISSUE THREAD

**Issue by flinz** [rossp/django-helpdesk#295]
https://github.com/rossp/django-helpdesk/commit/f0156cfcb3ca0337ed3fea556a814c566269d6fd changed the post_save connector of the usermodel to create a corresponding usersetting. 

However, in Django < 1.7 this fails if settings.AUTH_USER_MODEL is defined, since the sender is expected to be the actual instance, not a string. To be conform to https://docs.djangoproject.com/en/1.7/topics/auth/customizing/#referencing-the-user-model we need to check for django version explicitly and connect with the appropriate sender.

**Comment by JJediny** [comment]
Ran into this issue last week as a temporary solution consider adding an additional step at the end of the installation steps in README...
 
$`python manage.py create_usersettings`
