### ISSUE TITLE
socks_proxy_type needs to be included in 1.1.15 south migration pip release

### ISSUE THREAD

**Issue by iboulard** [rossp/django-helpdesk#303]
Please add the schema migration of socks_proxy_type for helpdesk_queue.
Thank you!

**Comment by flinz** [comment]
should have been addressed in https://github.com/rossp/django-helpdesk/commit/a87e1355eef831a865f9bebc6d7d5b43daa20044, i guess?

**Comment by iboulard** [comment]
How do I know if it is uploaded to PyPl live now? 
0010_auto__add_field_queue_socks_proxy_type__add_field_queue_socks_proxy_ho
When I installed 1.1.15 and ran the south migration it was not there this morning.
Thank you

**Comment by flinz** [comment]
these are post 1.1.15 commits, which are not yet part of a release. so you would have to re-install it directly from the master at github (via pip):
```pip uninstall django-helpdesk```
```pip install git+git://github.com:rossp/django-helpdesk.git```

**Comment by rossp** [comment]
Apologies for that - I have just pushed 0.1.16 which includes these.

**Comment by iboulard** [comment]
Wonderful! Thank you so much!
