### ISSUE TITLE
email in and out

### ISSUE THREAD

**Issue by rando305** [rossp/django-helpdesk#305]
So I can connect to my exchange server to receive emails and create tickets.  But, with the IMAP credentials that I am using to read emails, I am not succeeding to connect back to the server with the default EMAIL_BACKEND.  Is there a different EMAIL_BACKEND I should be using to reconnect to my email server and send from there?  Or should I just send through an SMTP server instead?

**Comment by rossp** [comment]
IMAP isn't used for sending email - django-helpdesk will use Django's default outgoing email handler. if you modify `EMAIL_BACKEND` that'll be used automatically; typically this would be an SMTP server (you can probably run Exchange in SMTP mode if it isn't already)

Double-check also that you can send e-mail from your Django install before getting django-helpdesk running. The first code example in the Django email docs should help: https://docs.djangoproject.com/en/1.7/topics/email/

**Comment by mrkiwi-nz** [comment]
Close this #worksforme ?

**Comment by rossp** [comment]
Agreed, this is a local configuration issue and doesn't need to be open here.
