### ISSUE TITLE
Update installation instructions to mention bootstrapform

### ISSUE THREAD

**Issue by andybak** [rossp/django-helpdesk#307]
I hit the same problem in #245 (which is closed).

This page: https://django-helpdesk.readthedocs.org/en/latest/install.html

doesn't mention adding bootstrapform

**Comment by rossp** [comment]
Check your attitude. This is a volunteer-run open source project and you’re commenting on a 4-year old task. Be productive, be polite, or be quiet.

**Comment by rossp** [comment]
Further - if you open the RTD link in the original issue above you’ll note that bootstrapform is included in INSTALLED_APPS. If you have some other issue, @jayturnr, I suggest you explain your issue and talk nicely so volunteers might be inclined to assist. Swearing at times is fine but personal abuse isn’t warranted and I will not stand for it.

**Comment by JayTurnr** [comment]
It just frustrates me to no end to see that the [hosted docs](http://django-helpdesk.readthedocs.org/) for a project are missing a vital step for setup, and then to see that people have said it needs to be fixed only for the issues to be closed without so much as a word.

**Comment by JayTurnr** [comment]
> Check your attitude. This is a volunteer-run open source project and you’re commenting on a 4-year old task. Be productive, be polite, or be quiet.

And you're right sorry.

**Comment by rossp** [comment]
Have you read the install link referenced above? In the link above bootstrapform is included. Your comments are entirely unfounded and it makes the personal abuse directed at me even more unacceptable.

**Comment by JayTurnr** [comment]
> Have you read the install link referenced above? In the link above bootstrapform is included. Your comments are entirely unfounded and it makes the personal abuse directed at me even more unacceptable.

Oh my god, I am fucking blind. I just looked at what was inline and not the actual code block (because most libraries show the bog standard included-with-django INSTALLED_APPS + their app)

I sincerly apologise. 

Tip to myself: Don't code while stressed, you say stupid and rude shit.

**Comment by rossp** [comment]
I hope you have learned from this. Apology accepted.
