### ISSUE TITLE
Template indentation

### ISSUE THREAD

**Issue by andybak** [rossp/django-helpdesk#309]
I'm having trouble reading the template code due to inconsistencies in indentation.

I'd quite like to reformat the source and send a pull request for this change. Would this be accepted? 

Is the preference for html indents 4 spaces or 2?

**Comment by rossp** [comment]
Please do! My preference is 4-space indents to match the Python code. If it's feasible for this to be a standalone pull request without any other changes that'd be absolutely awesome.

**Comment by mrkiwi-nz** [comment]
This looks to have been done somewhere along the way. Close the ticket?
