### ISSUE TITLE
Issue getting the Outbound Mail Server to send ticket confirmation/update emails

### ISSUE THREAD

**Issue by JJediny** [rossp/django-helpdesk#312]
### Followed the steps in the documentation including:
* The Django Project I'm using uses the following settings for the SMTP in local_settings.py

      EMAIL_USE_TLS = True
      EMAIL_HOST = 'smtp.gmail.com'
      EMAIL_HOST_USER = 'youremail@gmail.com'
      EMAIL_HOST_PASSWORD = 'yourpassword'
      EMAIL_PORT = 587

* $`python manage.py create_usersettings`
* $`python manage.py loaddata emailtemplate.json`

But still cannot get the SMTP emails to send out ticket confirmations nor updates? Any steps/config I'm missing and/or any advise to debug? Thanks in advance

**Comment by JJediny** [comment]
Just for context, I reviewed the tickets before submitting (namely #305) and I have the Inbound IMAP server working using `imap.gmail.com` and using gmail labels (note - use the exact lowcase label name as shown in gmails settings for IMAP folder name) to handle each queue type with a cron job setup and running to harvest... and I can verify that django was and is still able to send emails as the django project uses it to send out notifications.

**Comment by rossp** [comment]
Just so we're 100% clear - if you run `python manage.py shell` then execute the following, you receive the e-mail?

```python
from django.core.mail import send_mail
send_mail('Subject here', 'Here is the message.', 'queue_address@example.com', ['you@you.com',], fail_silently=False)
```

What about this?
`python manage.py shell`
```python
from django.core.mail import EmailMultiAlternatives
from django.conf import settings
sender = settings.DEFAULT_FROM_EMAIL
subject = 'Test email'
recipient = 'you@you.com'
sender = 'queue_address@blah.com'
body = 'This is the email body'
msg = EmailMultiAlternatives(subject, body, sender, [recipient,])
msg.send(fail_silently=False)
```

The former is a standard Django email, the latter is the way we send an email in django-helpdesk (we also attach a HTML part and do some templating etc - but that's the core of it). 

I'd double check your sender and recipient lists... perhaps django-helpdesk is emailing FROM your Queue address, but Gmail doesn't want you to use that as the sender? Try a few different values for `sender` above and test it out, keeping `fail_silently=False` to catch any issues.

**Comment by JJediny** [comment]
Thanks for the assist in debugging!... We went though a series of scenarios with them, it was an error in settings precedence as we use a django-project wrapper we have two local_settings.py & settings.py files with the email settings override not containing the TLS and SSL ports. Note for those looking at this that google will not support sending HTML emails using a TLS protocol/port only SSL. Some other helpful commands to run were:

          sudo find / -name "*.log" -type f -exec grep -iH "smtp" {} \;
          
What python files have EMAIL_USE in them?   

          sudo find / -name "*.py" -type f -exec grep -iH "email_use" {} \;

What logs have SMTP errors in them?

        sudo find / -name "*.log" -type f -exec grep -iH "smtp" {} \;

What log files have been opended most recently?
     
        /var/log# find . -type f -printf "%C@ %p\n" | sort -rn | head -n 10

Here are the settings that worked... 

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'email@gmail.com'
EMAIL_HOST_PASSWORD = 'pwd'
#Port for TLS
EMAIL_PORT = 587
#EMAIL_USE_TLS = True
#Port for SSL
#EMAIL_PORT = 465
#EMAIL_USE_SSL = True
