### ISSUE TITLE
Add support for Django 1.8

### ISSUE THREAD

**Issue by AntonOfTheWoods** [rossp/django-helpdesk#315]
There appear to be some incompatibilities with Django 1.8. I was able to get a basic install and create a ticket (with a couple of custom fields) but I had to fake the 0004 migration as it was hanging, and the migrate also errored on 0003 with "ValueError: Cannot query "User object": Must be "User" instance." (though didn't seem to mind when I retried and it moved to 0004). The two are probably related.

With the template changes in 1.8, there seem to need to be more than mere config/cosmetic changes that need to be made though - get_template_from_string has been completely removed to support multiple template engines, for one.

Unfortunately, my Python, Django and django-helpdesk knowledge are not sufficient for me to be able to offer anything more than nasty kludges, and it is probably worth seeing whether the email templating system could benefit from the new changes in Django 1.8. But that would require knowing how to support multiple Django versions with the changes, and all of this is outside my current skill level!

**Comment by HotPepperDaddy** [comment]
https://docs.djangoproject.com/en/1.8/ref/templates/upgrading/#get-template-from-string

**Comment by HotPepperDaddy** [comment]
Here's a temporary fix tha tonly works with the default template loader.  This is option 1 from the abover link.  I tried options 2 and 3 but they are a no go.  The real solution will be for helpdesk to implement a custom pluggable template loader that loads the string from the model and adds the footer or something.  I wouldn't release this code but it will be a working solution for many.

Index: helpdesk/lib.py
===================================================================
--- helpdesk/lib.py     (revision 380)
+++ helpdesk/lib.py     (working copy)
@@ -51,7 +51,7 @@
     """
     from django.conf import settings
     from django.core.mail import EmailMultiAlternatives
-    from django.template import loader, Context
+    from django.template import Context, engines

     from helpdesk.models import EmailTemplate
     from helpdesk.settings import HELPDESK_EMAIL_SUBJECT_TEMPLATE
@@ -85,7 +85,7 @@

     footer_file = os.path.join('helpdesk', locale, 'email_text_footer.txt')

-    text_part = loader.get_template_from_string(
+    text_part = engines['django'].from_string(
         "%s{%% include '%s' %%}" % (t.plain_text, footer_file)
         ).render(context)

@@ -100,11 +100,11 @@
         html_txt = html_txt.replace('\r\n', '<br>')
         context['comment'] = mark_safe(html_txt)

-    html_part = loader.get_template_from_string(
+    html_part = engines['django'].from_string(
         "{%% extends '%s' %%}{%% block title %%}%s{%% endblock %%}{%% block content %%}%s{%% endblock %%}" % (email_html_base_file, t.heading, t.html)
         ).render(context)

-    subject_part = loader.get_template_from_string(
+    subject_part = engines['django'].from_string(
         HELPDESK_EMAIL_SUBJECT_TEMPLATE % {
             "subject": t.subject,
         }).render(context)

**Comment by flinz** [comment]
Nice, I just replicated the exact same fix on my fork to get compatibility before seeing this :) I can thus confirm that options 2 and 3 are a no go.

**Comment by ssadler** [comment]
So, how's this going? Would be cool to get 1.8 support merged into master. Currently for my client I am using the 1.8 branch and it's pretty smooth sailing (knock on wood).

**Comment by flinz** [comment]
@rossp This can be closed.
