### ISSUE TITLE
Initial installation Django 1.6

### ISSUE THREAD

**Issue by Juan-redatlas** [rossp/django-helpdesk#324]
I use Django 1.6, and whe i do: ```./manage.py migrate helpdesk```
appear the next error:
```
File "/virtualenvFolder/lib/python2.6/site-packages/helpdesk/migrations/0001_initial.py", line 4, in <module>
from django.db import models, migrations
ImportError: cannot import name migrations
```
i need to upgrade to django 1.7?

**Comment by rossp** [comment]
Have you got the latest version of South installed?

**Comment by rossp** [comment]
This should no longer be an issue as we don't rely on `south` any more.
