### ISSUE TITLE
Sending Email

### ISSUE THREAD

**Issue by Reykoh** [rossp/django-helpdesk#325]
Hi, 
I have some issue to send mail through HelpDesk.
I added my email host and user identifications in settings.py and when I run ./manage.py shell, I can send mail.
In my followup list, I enabled the mail sending, but when a ticket is create, the creator doesn't receive an email... did I miss something? Is there something else to modify?
(sorry for my bad english)

Reykoh

**Comment by rossp** [comment]
What method are you using to send email? Is your queue configured with a valid e-mail address for your chosen email delivery service? (The queue email is used when sending email *from* the queue). Do any other emails get sent, ie on assignment, update, or close?

**Comment by 1keeganweber** [comment]
Hi Ross

Do you know if it is possible to compose normal emails from Django Help Desk for front end users?

Keegan

**Comment by rossp** [comment]
No, it's a helpdesk system not a full CRM or email client.
