### ISSUE TITLE
Only able to send mail if ticket is resolved

### ISSUE THREAD

**Issue by dominicfollett** [rossp/django-helpdesk#342]
If I update a ticket, or close it, or reopen it, no mail is sent to the ticket creator, however if I do resolve the ticket then a mail is sent. I can't figure out why this might be happening especially as I have made no changes to the app, and it was working very well for a couple of months. 

I have also testing sending mail this way with no issue at all : 

from django.core.mail import send_mail
send_mail('Subject here', 'Here is the message.', 'queue_address@example.com', ['you@you.com',], fail_silently=False)
What about this?
python manage.py shell

AND

from django.core.mail import EmailMultiAlternatives
from django.conf import settings
sender = settings.DEFAULT_FROM_EMAIL
subject = 'Test email'
recipient = 'you@you.com'
sender = 'queue_address@blah.com'
body = 'This is the email body'
msg = EmailMultiAlternatives(subject, body, sender, [recipient,])
msg.send(fail_silently=False)

Is there anything that might be causing this behaviour?

EDIT

doing some debugging I found this being returned when I try and update the ticket:

WARNING:helpdesk:template "updated_submitter" does not exist, no mail sent

**Comment by flinz** [comment]
Can you check in your database whether the table ```helpdesk_emailtemplate``` contains any rows?
Could be that you somehow messed up entries in there - e.g. the table should contain an entry with id 16, which is the ```updated_submitter``` template.

If so, you probably want to reimport the data from https://github.com/rossp/django-helpdesk/blob/master/helpdesk/fixtures/emailtemplate.json to reset the behavior.

**Comment by dominicfollett** [comment]
Yeah someone deleted the template :-1:  argh. Marking this as resolved.
