### ISSUE TITLE
Stats not working when user name or queue names have utf-8 characters

### ISSUE THREAD

**Issue by Ardrake** [rossp/django-helpdesk#345]
Django 1.7.8
Phthon 2.7.8
psycopg2==2.6.1 -> Postgres database 

Everything is working great, with the exception of the stats screens, they remain at 0, for all stats.

have tried these settings, to no avail

HELPDESK_NAVIGATION_STATS_ENABLED = True
HELPDESK_ENABLE_PER_QUEUE_MEMBERSHIP = True

**Comment by Ardrake** [comment]
When switching to english language I get partial stats, all stats not assigned to a user are showing up.

**Comment by reduxionist** [comment]
Andre,

Unless you intend to restrict users to only be able to see those queues you have explicitly granted them access to, you do not want:

**Comment by Ardrake** [comment]
Thanks for the quick response, ok, switched to 

HELPDESK_ENABLE_PER_QUEUE_MEMBERSHIP = False

Still not wroking as intended as en example

LANGUAGE_CODE = 'fr-CA'
![screen02](https://cloud.githubusercontent.com/assets/4698209/10908445/03b9b290-8200-11e5-9856-e10ad19d89af.jpg)

LANGUAGE_CODE = 'en-US'
![screen01](https://cloud.githubusercontent.com/assets/4698209/10908457/1246fac0-8200-11e5-9dea-d8bac9cda72e.jpg)

I'm thinking perhaps an encoding issue, then again this is a guess, I have not looked deeper in the issue.

**Comment by reduxionist** [comment]
The next step then would be to install the [django-debug-toolbar](https://github.com/django-debug-toolbar/django-debug-toolbar) and compare the debug output (esp. SQL queries) generated by the English and French versions. Bon chance! :)

**Comment by Ardrake** [comment]
Changed my name in the admin file, removed the utf-8 characters, André switch to Andy
and voila, I have some stats to my name, the Queries under django-debug-toolbar are identical.

LANGUAGE_CODE = 'en-US'
![screen03](https://cloud.githubusercontent.com/assets/4698209/10908975/97bdf17e-8203-11e5-9c00-82d56f744e28.jpg)

LANGUAGE_CODE = 'fr-CA'
![screen04](https://cloud.githubusercontent.com/assets/4698209/10909049/1687f95a-8204-11e5-9d1d-56745ad16ef4.jpg)

**Comment by rossp** [comment]
Thanks for narrowing this down. I'll try to investigate in the next 24 hours.

**Comment by flinz** [comment]
In the light of this and https://github.com/rossp/django-helpdesk/pull/356 we should probably add some tests for non-unicode stats generation.

**Comment by rossp** [comment]
I believe this has been addressed with the introduction of Python 3 support in django-helpdesk (see #290). Thanks, @flinz
