### ISSUE TITLE
unable to send mail while ticket generating or updated

### ISSUE THREAD

**Issue by i25** [rossp/django-helpdesk#348]
that is my setting.py configuration 

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'xxxxxx@gmail.com'
EMAIL_HOST_PASSWORD = 'xxxxx'
#Port for TLS
EMAIL_PORT = 587

**Comment by Ardrake** [comment]
Add this setting for use with GMAIL


EMAIL_USE_TLS = True

**Comment by Ardrake** [comment]
You might also need to activate third party mail acces thru your GMAIL account

**Comment by i25** [comment]
POP Download:
Learn more	
1. Status: POP is enabled for all mail that has arrived since 1/22/08
	Enable POP for all mail (even mail that's already been downloaded)
	Enable POP for mail that arrives from now on
	Disable POP

2. When messages are accessed with POP

3. Configure your email client (e.g. Outlook, Eudora, Netscape Mail)
Configuration instructions
IMAP Access:
(access Gmail from other clients using IMAP)
Learn more	
Status: IMAP is enabled
	Enable IMAP
	Disable IMAP

When I mark a message in IMAP as deleted:
	Auto-Expunge on - Immediately update the server. (default)
	Auto-Expunge off - Wait for the client to update the server.

When a message is marked as deleted and expunged from the last visible IMAP folder:
	Archive the message (default)
	Move the message to the Trash
	Immediately delete the message forever

Folder Size Limits
	Do not limit the number of messages in an IMAP folder (default)
	Limit IMAP folders to contain no more than this many messages

Configure your email client (e.g. Outlook, Thunderbird, iPhone)
Configuration instructions

**Comment by i25** [comment]
but same issue occur

**Comment by Ardrake** [comment]
From a previous issue with same problem

https://github.com/rossp/django-helpdesk/issues/312

* * *
Run the shell

python manage.py shell

from django.core.mail import EmailMultiAlternatives
from django.conf import settings
sender = settings.DEFAULT_FROM_EMAIL
subject = 'Test email'
recipient = 'you@you.com'
sender = 'queue_address@blah.com'
body = 'This is the email body'
msg = EmailMultiAlternatives(subject, body, sender, [recipient,])
msg.send(fail_silently=False)

* * *

This is how I got mine working, it should help you figure out where it is broken

**Comment by i25** [comment]
thank a lot for solution but error occurs

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/django/core/mail/message.py", line 303, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python2.7/dist-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python2.7/dist-packages/django/core/mail/backends/smtp.py", line 67, in open
    self.connection.login(self.username, self.password)
  File "/usr/lib/python2.7/smtplib.py", line 615, in login
    raise SMTPAuthenticationError(code, resp)
SMTPAuthenticationError: (534, '5.7.14 <https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbtMB\n5.7.14 lmDRwskyn4DaXdY1pta5oS1UN0qWOMqNXfKz38FFLoIfhkf7C7HyAD2de6iq_kte1h_hPB\n5.7.14 PnNIobzGq7_O8jQooKPcnLLpol5K7Sgq2V-unxdvbFUfCm8rnsTL9woV2ML7Us7hkUbDRn\n5.7.14 8TPcUMR7fQapKJwn4dIP7YaJdbH1RtuMDYJLvyclcWt7g99PN82guM5sY_CkcqSbwIYgwu\n5.7.14 8EmVcO8NQcE3qEdAhCZbBl3RNzfw> Please log in via your web browser and\n5.7.14 then try again.\n5.7.14  Learn more at\n5.7.14  https://support.google.com/mail/answer/78754 sg4sm102692pac.48 - gsmtp')

**Comment by Ardrake** [comment]
your answer is in the message....

SMTPAuthenticationError

see
https://support.google.com/mail/answer/78754
 for solution

**Comment by i25** [comment]
thank for quick reply and i configured less security devices and test mail works but mail unable to send mail via updation and view the ticket

**Comment by rossp** [comment]
This appears to be an issue with Gmail (specifically, with your Gmail account or with your Python configuration to email through Gmail) and is not specific to django-helpdesk. As per issue #312 you can manually try to send email and take note of the error messages provided.

I don't want to discourage participation in open source software however we cannot provide a high level of support (especially relating to third party services) as volunteers. django-helpdesk is a beta-quality product and although it works well for some people, it might need a bit more hands-on work to set up and to maintain on an ongoing basis. This is unfortunate but it is a reality for this project at this time.

If you encounter any further issues that are specific to django-helpdesk please log them, however this item does not currently appear to fall into that category.
