### ISSUE TITLE
Private comments

### ISSUE THREAD

**Issue by jstnk9** [rossp/django-helpdesk#357]
Hello!

Can i a send private comment for some user only?

I talk about tickets 

thx!

**Comment by rossp** [comment]
Private comments are visible to staff, and Public comments are also visible to the submitter. Think of them as "Staff Only" or "Staff + Submitter".

**Comment by jstnk9** [comment]
Thanks for your quick answer

I created a new column in the table helpdesk_ticket, where the query is to store values?.

Regards.

**Comment by reduxionist** [comment]
@jstnk9 

It sounds like you are trying to add new functionality by directly altering the database but this is not how Django applications are built. Django uses an Object-Relational Mapper (ORM) so the preferred way to add a column to a table is to add a field to the corresponding model class (see helpdesk/models.py: class Ticket). The corresponding behaviour can also be encapsulated in that same model class.

The queries to store and retrieve values are generated through calls to the ORM (via the corresponding model class), not by making SQL queries directly. I recommend you familiarise yourself with the Django documentation first before adding new features to django-helpdesk: https://docs.djangoproject.com/

Good luck!

**Comment by jstnk9** [comment]
@reduxionist 

Thank you very very much

I found the solution! :+1: 

Regards Sir!
