### ISSUE TITLE
Relate Queue permissions with Django admin built-in permissions

### ISSUE THREAD

**Issue by alexbarcelo** [rossp/django-helpdesk#359]
I was thinking on the possibility to use Django permission system in order to decide if a user or a group can access a certain Ticket.

That would allow a more fine-grain access to tickets (in a per-object basis), would become a valid and a more "safe" ACL --if I understand correctly, the current approach of QueueMembership is used for load distribution purposes, not for security.

However, before starting the implementation and doing a pull request, I was interested in hearing some opinions, if this has been tried or if there are some pitfalls that make this difficult / unacceptable.

[One reason of doing this is that I needed to give permission per-group instead of per-user, which I know could be patched into the QueueMembership implementation, but I was thinking on this approach and wanted some feedback before deciding implementation]

**Comment by reduxionist** [comment]
@alexbarcelo Django's built-in permission system only provides per-table, not per-row, access control and so would be unable to provide the functionality you desire (i.e. create or edit or delete authorization is only granted for all tickets or for none).

I would recommend using [django-guardian](https://github.com/django-guardian/django-guardian) for more granular auth.

**Comment by alexbarcelo** [comment]
@reduxionist Let me explain a little bit, because Django has mechanism for per-row edit access control, but it is not implemented by default.

Regarding the admin views, there is the underused method: `has_change_permission` for the model admin. This doesn't prevent people with edit rights onto the Tickets table from seeing the full list in the admin views, but can prevent people with such rights from accessing individual tickets if they are not in their allowed queues. Thus, implementing `has_change_permission` for individual Tickets objects can disable the edit from unprivileged users. I think that this is a quite reasonable and expected behaviour (I would add a Queue column in the admin views, just in case).

On the other hand, on the helpdesk views, instead of consulting the QueueMembership you can query the Django auth permissions and you can force the expected behaviour. In fact, something similar is being done at some points but with the `user.queuemembership` field.

**Comment by alexbarcelo** [comment]
I added a PR #363 using the "Permission" approach. It is a quite nice feature in my deployment and I will probably end up using it in any case.

**Comment by rossp** [comment]
I think I can see this working and there's a benefit to using the Django tools rather than reinventing the wheel, however we need to have a documented migration process from the current model. This can either be via a Django migration, or a documented set of scripts to create + assign permissions when appropriate.

**Comment by alexbarcelo** [comment]
Ok, thanks for the feedback! If you think it's valuable I will try to add
ASAP a Django migration for automatic migration from the previous approach
to the new approach.

The QueueMembership is simple in its relations, so it should not be hard to
adapt. I will add some documentation regarding this feature and its
counterpart.

**Comment by alexbarcelo** [comment]
I have already proposed the PR #363 so I suppose that this ticket can be closed.
