### ISSUE TITLE
Bug: Integer given as string in models.py

### ISSUE THREAD

**Issue by flinz** [rossp/django-helpdesk#360]
Thanks to @alexbarcelo for [spotting this](https://github.com/rossp/django-helpdesk/issues/355#issuecomment-164671890).

https://github.com/flinz/django-helpdesk/blob/django-1.9-fixes/helpdesk/models.py#L1216 has ``max_length`` given as a string. This seems to work for MYSQL, however might cause problems in PostgreSQL.

Since it's the only instance of max_length given by a string in models.py, I suggest to just change it to int.

**Comment by alexbarcelo** [comment]
This seems to prevent any database operation (`syncdb` or migrate-related stuff) in my production environment, which is Django 1.9 and PostgreSQL.

Changing `Django==1.8` in my requirements seems to make it work (maintaining the Postgres database). So I am not sure if it is some combination of factors or what.

However, as you said, it is the only instance of `max_length` given by a string, so your bugfix seems the sensible approach. Thanks a lot!

**Comment by flinz** [comment]
Ah, in this case I will move the bugfix into the django 1.9 PR.

**Comment by alexbarcelo** [comment]
wait, wrong test, give me a couple of minutes, maybe I'm mistaken

**Comment by alexbarcelo** [comment]
Sorry about that, I had just realized that the `requirements.txt` was not in a "consistent state", and wanted to make sure that what I said it was true. Now I have checked with Django==1.8, master branch and Postgres and it seems to work. So the is indeed for Django 1.9 compatibility, related to Postgres usage it seems.

Thanks again and sorry for the fuss

**Comment by flinz** [comment]
Ok, thanks for double checking.
