### ISSUE TITLE
Add permissions even if HELPDESK_ENABLE_PER_QUEUE_STAFF_PERMISSION=False

### ISSUE THREAD

**Issue by flinz** [rossp/django-helpdesk#368]
I think it would make sense to add the corresponding permission for Queues upon creation, *even if the option is disabled in the settings*. Otherwise, if users choose to enable this functionality after a while, there are no permissions that I can assign to users, since my existing queues have not had their permissions created alongside.

I.e. the line https://github.com/rossp/django-helpdesk/blob/master/helpdesk/models.py#L281 should be removed.

@alexbarcelo are there any other lines that I would be missing?

**Comment by alexbarcelo** [comment]
Now that you mention it... it would make sense, the migration will be simpler and is is more difficult for the sysadmin to break things.

I thought about that but was afraid of adding an overwhelming quantity of permissions. But the number of Queues should not be huge, and there should be no impact if `STAFF_PERMISSION=False`

I will prepare a PR doing this, and meanwhile we can discuss if there is some problem about creating unnecessary permissions. I don't think that this creation is really a problem, and as your use case showed, it is a pain to fix afterwards.
