### ISSUE TITLE
Django 1.8 - python 2.7 fails with release in 1.16

### ISSUE THREAD

**Issue by rando305** [rossp/django-helpdesk#371]
Is there a plan for a new release.  I see some of the errors have been corrected in the current code.

**Comment by alexbarcelo** [comment]
See #362 

@rossp commented something about next week. You are welcome to test (for instance I am currently using the master branch in our development environment's `requirements.txt` in order to check that everything goes smoothly)

**Comment by flinz** [comment]
@rando305 as @alexbarcelo said, the master branch should fix most problems with Django 1.8. Please let us know should you still encounter any bugs!

**Comment by rando305** [comment]
Thank you.  I am using the master branch I have two problems.

Line 1401 and 1429 of view/staff.py  

it doesn't like Tickets.exclude and Tickets.filter.  When I change it to Tickets.objects.exclude it works fine.

Did something change in Django?  I'm using 1.8 with python 2.7

**Comment by flinz** [comment]
@rando305 

- Could you help me reproduce this? When does this occur? Right away when you e.g. ``./manage.py runserver``, or when you perform a certain action?
- Could you please run ``./manage.py test helpdesk`` and tell me if this fails?

**Comment by alexbarcelo** [comment]
I was looking around and it seems that the function `calc_basic_ticket_stats` is only called from the `dashboard` view, and the argument `Tickets` is a Django QuerySet. (Caution! `Ticket` is the model, `Tickets` is the argument of the function).

A Django QuerySet should have the methods `exclude` and `filter` and should not have the property `objects`, so I am not sure what's happening. @flinz has already suggested some steps in order to troubleshoot the problem.

**Comment by rando305** [comment]
@flinz when I pull up the dashboard.

**Comment by rando305** [comment]
@flinz - is there a user flag necessary to run the test?  I get a bunch of Attribute Errors: "WSGIRequest" object has no attribute 'user'

**Comment by flinz** [comment]
@rando305

- are you sure you cloned the master branch from github and are using that as the codebase for helpdesk? Just making sure before I investigate this further. 

To debug the problems you have with the tests, should the answer be yes to the aboce:
- can you upload a sqlite of a database you are using (of course without any sensitive data) 

- which django are you using? I assume the latest 1.8.7?

**Comment by rando305** [comment]
@flinz - yes, i made special effort to get the latest code - because the other was giving errors, that the master had fixed. 
I'm using 1.8.7 django.  
How would I capture the sqlite db prior to test killing it?

**Comment by rando305** [comment]
@alexbarcelo  @flinz ,  in the dashboard view, Ticket is being passed as the parameter into calc_basic_ticket_stats.  Ticket isn't a queryset, it's the model.

**Comment by flinz** [comment]
Let's try something before: did you run ``manage.py migrate``? 

Are you using sqlite or mysql?

**Comment by alexbarcelo** [comment]
@rando305 at line 120 in the dashboard view: https://github.com/rossp/django-helpdesk/blob/master/helpdesk/views/staff.py

    Tickets = Ticket.objects.filter(
                queue__in=user_queues,
            )
    basic_ticket_stats = calc_basic_ticket_stats(Tickets)

Tickets is a QuerySet. Could you point me which line are you referring to?

**Comment by rando305** [comment]
It's my code calling calc_basic_ticket_stats.

problem solved.  (I didn't write the code ...)  So instead of sending in Ticket - I should send in a queryset.  Should I just send Ticket.objects.all()?

**Comment by alexbarcelo** [comment]
Well, that depends on what you are trying to accomplish. But if you want to pass all the tickets, then it is correct to use `Ticket.objects.all()`.

**Comment by rando305** [comment]
ok - thanks for your help.  I'll check to see if any further filtering is available at that point in the code.
