### ISSUE TITLE
syntax error at or near ")"

### ISSUE THREAD

**Issue by N3TC4T** [rossp/django-helpdesk#383]
Hey 
can you help to  handle this ?

>ProgrammingError at /helpdesk/dashboard/
 syntax error at or near ")"
LINE 10:                     q.id IN ()

https://github.com/rossp/django-helpdesk/commit/fb66fea86ed17150406bf327afeafce0128c4e46#diff-894294424769a5a4786e12d915712494R135

**Comment by N3TC4T** [comment]
my bad
i've forget to add que

**Comment by AnimalInstinct** [comment]
Can you explain please , how to fix it?
