### ISSUE TITLE
HAS_TAG_SUPPORT - Does this work?

### ISSUE THREAD

**Issue by daela** [rossp/django-helpdesk#418]
I noticed the HAS_TAG_SUPPORT in settings.py    Changing this to TRUE does not seem to do anything for me. Should this option work? Am I missing something? I was hoping it would allow me to tag tickets to provide some additional filtering/reports.

**Comment by rossp** [comment]
This no longer does anything - there used to be support for django-tagging and/or django-taggit in various ways that has since been removed due to issues relying on the third party apps at the time, iirc.

**Comment by daela** [comment]
Ok. Thanks for the reply.
